"""add planned_start_date to treatment_cases

Revision ID: 28f4f2a5e915
Revises: a0f61078f906
Create Date: 2026-09-01 12:03:16.195599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f4f2a5e915'
down_revision: Union[str, None] = 'a0f61078f906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_cases', sa.Column('planned_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_cases', 'planned_start_date')
    # ### end Alembic commands ###
