"""initial schema: patients, treatment_cases, machine_slots, sessions, source_documents

Revision ID: a0f61078f906
Revises: 
Create Date: 2026-08-28 11:44:53.247382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0f61078f906'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_date', 'time_start', name='uq_machine_slot_date_start')
    )
    op.create_index(op.f('ix_machine_slots_slot_date'), 'machine_slots', ['slot_date'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_iin'), 'patients', ['iin'], unique=True)
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflict_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by_doctor', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('diagnosis_text', sa.String(length=1000), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('treatment_modality', sa.String(length=20), nullable=False),
    sa.Column('clinical_pathway', sa.String(length=30), nullable=True),
    sa.Column('urgency_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_category', sa.String(length=20), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('has_signal_conflict', sa.Boolean(), nullable=False),
    sa.Column('sessions_required', sa.Integer(), nullable=False),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.Column('fractions_per_week', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('clinical_deadline_date', sa.Date(), nullable=True),
    sa.Column('confirmed_by_doctor', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_cases_patient_id'), 'treatment_cases', ['patient_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('treatment_case_id', sa.UUID(), nullable=False),
    sa.Column('machine_slot_id', sa.UUID(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_slot_id'], ['machine_slots.id'], ),
    sa.ForeignKeyConstraint(['treatment_case_id'], ['treatment_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_slot_id')
    )
    op.create_index(op.f('ix_sessions_treatment_case_id'), 'sessions', ['treatment_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_treatment_case_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_treatment_cases_patient_id'), table_name='treatment_cases')
    op.drop_table('treatment_cases')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_patients_iin'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_machine_slots_slot_date'), table_name='machine_slots')
    op.drop_table('machine_slots')
    # ### end Alembic commands ###
